name: "PixelEachSubstitutor"

params:
  n_trials: 2
  hyperparams_for_each_cell: [
    {
      n_range_search: 0,
      max_width: 1,
      max_height: 1,
      L_dims_encoded: [1],
      pad_n_head: 1,
      L_num_layers: 4,
    },
    {
      n_range_search: 1,
      max_width: 3,
      max_height: 3,
      L_dims_encoded: [9],
      pad_n_head: null,
      L_num_layers: 4,
    },
  ]
  max_epochs_for_each_task: 300
  train_loss_threshold_to_stop: 0.01
