name: "PixelEachSubstitutor"

params:
  n_trials: 2
  hyperparams_for_each_cell: [
    # {
    #   n_range_search: 0,
    #   W_kernel_max: 1,
    #   H_kernel_max: 1,
    #   L_dims_encoded: [1],
    #   L_num_layers: 4,
    # },
    # {
    #   n_range_search: 1,
    #   W_kernel_max: 3,
    #   H_kernel_max: 3,
    #   L_dims_encoded: [9],
    #   L_num_layers: 4,
    # },
  ]
  train_loss_threshold_to_stop: 0.01
  max_epochs_for_each_task: 300
