name: "PixelEachSubstitutorRepeat"

params:
  W_max: 7
  H_max: 7
  n_range_search: 0
  W_kernel_max: 1
  H_kernel_max: 1
  C_encode: True
  C_dims_encoded: [10, 2]
  L_encode: True
  L_dims_encoded: [50, 9] # (7*7) + (3*36
  L_dims_decoded: [50, 1] # (7*7) + (3*3)
  pad_class_initial: -1
  pad_num_layers: 1
  pad_n_head: null
  pad_dim_feedforward: 1
  L_num_layers: 1
  L_n_head: null
  L_dim_feedforward: 1
  C_num_layers: 1
  C_n_head: null
  C_dim_feedforward: 1
  dropout: 0.0
  n_class: 10
