name: "PixelEachSubstitutor"

params:
  n_range_search: 1
  max_width: 3
  max_height: 3
  skip_sampler: False # Can solve the f76d97a5
  L_dims_encoded: [9]
  L_dims_decoded: [1]
  pad_class_initial: 0
  pad_num_layers: 1
  pad_n_head: null
  pad_dim_feedforward: 1
  L_num_layers: 6
  L_n_head: null
  L_dim_feedforward: 1
  C_num_layers: 1
  C_n_head: null
  C_dim_feedforward: 1
  dropout: 0.1
  n_class: 10

  n_trials: 1
  hyperparams_for_each_trial: [
    {
      n_range_search: 0,
      max_width: 1,
      max_height: 1,
      L_dims_encoded: [1],
      pad_n_head: 1,
      L_num_layers: 4,
    },
    {
      n_range_search: 1,
      max_width: 3,
      max_height: 3,
      L_dims_encoded: [9],
      pad_n_head: null,
      L_num_layers: 4,
    },
  ]
  max_epochs_for_each_task: 3
  train_loss_threshold_to_stop: 0.01
