name: "PixelEachSubstitutorRepeatNonColorEncoding"

params:
  n_range_search: 1
  max_width: 3
  max_height: 3
  encode_location: True
  L_dims_encoded: [32, 16]
  L_dims_decoded: [1]
  pad_class_initial: -1
  pad_num_layers: 1
  pad_n_head: null
  pad_dim_feedforward: 1
  L_num_layers: 1
  L_n_head: null
  L_dim_feedforward: 1
  C_num_layers: 1
  C_n_head: null
  C_dim_feedforward: 1
  dropout: 0.1
  n_class: 10

  n_trials: 0
  hyperparams_for_each_trial: []
  max_epochs_for_each_task: 100
  train_loss_threshold_to_stop: 0.01

  max_AFS: 100 # AFS: Accuracy First Search
  max_queue: 20
  max_depth: 30
