name: "PixelEachSubstitutorRepeat"

params:
  n_range_search: 1
  W_kernel_max: 3
  H_kernel_max: 3

  vec_abs: False
  W_max: 7
  H_max: 7

  C_encode: True
  C_dims_encoded: [10, 2]
  emerge_color: True

  L_encode: True
  L_dims_encoded: [9, 9] # L_dims_encoded[0] = (W_max*H_max if vec_abs else 0) + W_kernel_max*H_kernel_max
  L_dims_decoded: [9, 1] # L_dims_decoded[0] = (W_max*H_max if vec_abs else 0) + W_kernel_max*H_kernel_max

  pad_class_initial: -1
  pad_num_layers: 1
  pad_n_head: null
  pad_dim_feedforward: 1

  L_num_layers: 1
  L_n_head: null
  L_dim_feedforward: 1
  C_num_layers: 1
  C_n_head: null
  C_dim_feedforward: 1
  dropout: 0.0
  n_class: 10
