name: "PixelEachSubstitutor"

params:
  n_range_search: 1
  max_width: 3
  max_height: 3
  C_dims_encoded: [2]
  L_dims_encoded: [9]
  L_dims_decoded: [1]
  pad_class_initial: -1
  pad_num_layers: 1
  pad_n_head: null
  pad_dim_feedforward: 1
  L_num_layers: 1
  L_n_head: null
  L_dim_feedforward: 1
  C_num_layers: 1
  C_n_head: null
  C_dim_feedforward: 1
  dropout: 0.1
  n_class: 10
